LOUDNESS_ZWST_STRING = "LOUDNESS_ZWST"
ROUGHNESS_DW_STRING = "ROUGHNESS_DW"
SHARPNESS_DIN_STRING = "SHARPNESS_DIN"

GENERAL_FOLDERS = [LOUDNESS_ZWST_STRING, ROUGHNESS_DW_STRING, SHARPNESS_DIN_STRING]

SHARPNESS_DIN_WEITHING = ["din", "aures", "fastl"]